### ISSUE TITLE
Uninitialized values in tld-tree.c

### ISSUE THREAD

**Issue by jdiner** [stricaud/faup#83] opened 2017-02-27 15:09 UTC
Valgrind reports uninitialized values in tld-tree.c.  Here is the Valgrind report, trimmed to the stack frames within libfaup:

==14493== Conditional jump or move depends on uninitialised value(s)
==14493==    at 0x65EB75: faup_tld_tree_tld_exists (tld-tree.c:295)
==14493==    by 0x65EB75: faup_tld_tree_extract (tld-tree.c:406)
==14493==    by 0x65D1CE: faup_decode (decode.c:228)

==14493== Invalid read of size 1
==14493==    at 0x65EB61: faup_tld_tree_tld_exists (tld-tree.c:295)
==14493==    by 0x65EB61: faup_tld_tree_extract (tld-tree.c:406)
==14493==    by 0x65D1CE: faup_decode (decode.c:228)

==14493== Conditional jump or move depends on uninitialised value(s)
==14493==    at 0x65EA04: faup_tld_tree_extract (tld-tree.c:373)
==14493==    by 0x65D1CE: faup_decode (decode.c:228)

==14493== Use of uninitialised value of size 8
==14493==    at 0x65EA75: faup_tld_tree_tld_exists (tld-tree.c:295)
==14493==    by 0x65EA75: faup_tld_tree_extract (tld-tree.c:381)
==14493==    by 0x65D1CE: faup_decode (decode.c:228)

**Comment by stricaud** [comment] 2017-04-01 04:33
I could not reproduce with valgrind here, but I did see the comparison pointer not being initialized. I changed that so it should fix it. Can you give a try? If not, could you provide me the url you are using to run this?
Thanks!

**Comment by stricaud** [comment] 2020-05-12 04:47
no news, good news? I am closing this as this should be fine, however please re-open if you notice this again.

**Closed by stricaud** 2020-05-12 04:47 UTC
